export const rows = [
    {
      id: 1,
      Name: "John Doe",
      Email: "john.doe@example.com",
      Age: 30,
      Phone: "(555) 123-4567",
      Access: "Admin",
    },
    {
      id: 2,
      Name: "Jane Smith",
      Email: "jane.smith@example.com",
      Age: 25,
      Phone: "(555) 234-5678",
      Access: "User",
    },
    {
      id: 3,
      Name: "Samuel Green",
      Email: "samuel.green@example.com",
      Age: 28,
      Phone: "(555) 345-6789",
      Access: "User",
    },
    {
      id: 4,
      Name: "Emily White",
      Email: "emily.white@example.com",
      Age: 35,
      Phone: "(555) 456-7890",
      Access: "Admin",
    },
    {
      id: 5,
      Name: "Michael Brown",
      Email: "michael.brown@example.com",
      Age: 40,
      Phone: "(555) 567-8901",
      Access: "Manager",
    },
    {
      id: 6,
      Name: "Sarah Black",
      Email: "sarah.black@example.com",
      Age: 22,
      Phone: "(555) 678-9012",
      Access: "User",
    },
    {
      id: 7,
      Name: "David Blue",
      Email: "david.blue@example.com",
      Age: 31,
      Phone: "(555) 789-0123",
      Access: "Admin",
    },
    {
      id: 8,
      Name: "Sophia Red",
      Email: "sophia.red@example.com",
      Age: 27,
      Phone: "(555) 890-1234",
      Access: "Manager",
    },
    {
      id: 9,
      Name: "James Gray",
      Email: "james.gray@example.com",
      Age: 33,
      Phone: "(555) 901-2345",
      Access: "User",
    },
    {
      id: 10,
      Name: "Olivia Yellow",
      Email: "olivia.yellow@example.com",
      Age: 26,
      Phone: "(555) 012-3456",
      Access: "Admin",
    },
    // Nouveaux exemples ajoutés
    {
      id: 11,
      Name: "Jack Black",
      Email: "jack.black@example.com",
      Age: 29,
      Phone: "(555) 567-2345",
      Access: "Manager",
    },
    {
      id: 12,
      Name: "Lily White",
      Email: "lily.white@example.com",
      Age: 24,
      Phone: "(555) 678-3456",
      Access: "User",
    },
    {
      id: 13,
      Name: "James Bond",
      Email: "james.bond@example.com",
      Age: 40,
      Phone: "(555) 123-7890",
      Access: "Admin",
    },
    {
      id: 14,
      Name: "Olivia Brown",
      Email: "olivia.brown@example.com",
      Age: 28,
      Phone: "(555) 890-4567",
      Access: "Manager",
    },
    {
      id: 15,
      Name: "Ethan White",
      Email: "ethan.white@example.com",
      Age: 32,
      Phone: "(555) 234-8901",
      Access: "User",
    },
    {
      id: 16,
      Name: "Emma Green",
      Email: "emma.green@example.com",
      Age: 26,
      Phone: "(555) 345-2345",
      Access: "User",
    },
    {
      id: 17,
      Name: "Sophia Black",
      Email: "sophia.black@example.com",
      Age: 37,
      Phone: "(555) 456-3456",
      Access: "Manager",
    },
    {
      id: 18,
      Name: "Ava Blue",
      Email: "ava.blue@example.com",
      Age: 22,
      Phone: "(555) 567-7890",
      Access: "User",
    },
    {
      id: 19,
      Name: "Lucas White",
      Email: "lucas.white@example.com",
      Age: 38,
      Phone: "(555) 678-2345",
      Access: "Admin",
    },
    {
      id: 20,
      Name: "Mia Red",
      Email: "mia.red@example.com",
      Age: 29,
      Phone: "(555) 789-3456",
      Access: "Manager",
    },
  ];
  export  const columns = [
    { 
      field: "id", 
      headerName: "ID", 
      width: 33, 
      align: "center", 
      headerAlign: "center" 
    },
    { 
      field: "Name", 
      headerName: "Name", 
      flex: 1, 
      align: "center", 
      headerAlign: "center" 
    },
    { 
      field: "Email", 
      headerName: "Email", 
      flex: 1, 
      align: "center", 
      headerAlign: "center" 
    },
    { 
      field: "Age", 
      headerName: "Age", 
      flex: 1, 
      align: "center", 
      headerAlign: "center" 
    },
    { 
      field: "Phone", 
      headerName: "Phone", 
      flex: 1, 
      align: "center", 
      headerAlign: "center" 
    },
    { 
      field: "Access", 
      headerName: "Access", 
      flex: 1, 
      align: "center", 
      headerAlign: "center", 
             
    },
  ];
